// Explicit live staging runner. Not discovered by the synthetic regression runner.
// Secrets stay in disposable browser/worker memory; stdin commands are never echoed.
const fs=require('fs'),readline=require('readline'),{chromium}=require('playwright');
const STAGE='https://uffvbfmfsesdhjzzjiyu.supabase.co',PRODUCTION='https://aefhjgmiwgajdhgyhelm.supabase.co';
const origin=process.env.QA_BASE_URL,email=process.env.QA_TEST_EMAIL;
if(!origin||new URL(origin).hostname!=='clean-time-git-codex-welcome-backup-date-nu-cielo.vercel.app'||!email)throw new Error('Explicit PR staging origin and designated mailbox required');
const lines=readline.createInterface({input:process.stdin,terminal:false}),iterator=lines[Symbol.asyncIterator]();
let phase='start',passed=0,browser,productionAttempts=0,failWrite=false,authErrors=[];
const record=(v,label)=>{if(!v)throw new Error(label);passed++;process.stdout.write(JSON.stringify({pass:label})+'\n');};
async function command(next){phase=next;process.stdout.write(JSON.stringify({awaiting:next})+'\n');const {value,done}=await iterator.next();if(done)throw new Error('Missing private input');return JSON.parse(value);}
async function context(){const c=await browser.newContext({viewport:{width:360,height:800}});await c.route('**/*',r=>{
 const u=new URL(r.request().url());
 if(u.origin===PRODUCTION){productionAttempts++;return r.abort();}
 if(u.origin===origin)return r.continue({headers:{...r.request().headers(),'x-vercel-trusted-oidc-idp-token':process.env.VERCEL_OIDC_TOKEN}});
 if(u.origin===STAGE){if(failWrite&&u.pathname==='/rest/v1/user_data'&&['POST','PATCH'].includes(r.request().method()))return r.abort();return r.continue();}
 if(u.origin==='https://cdn.jsdelivr.net'&&u.pathname.includes('/@supabase/supabase-js@2.117.2/'))return r.continue();
 return r.abort();});return c;}
async function receiveLink(p,next){const data=await command(next);if(process.env.QA_MANUAL_EMAIL){await p.locator('#account').waitFor({state:'visible',timeout:300000});record(await p.evaluate(()=>!location.hash),'User email callback clears token URL');return;}const u=new URL(data.url);if(u.origin!==STAGE||u.pathname!=='/auth/v1/verify'||u.searchParams.get('redirect_to')!==origin)throw new Error('Unexpected verification destination');await p.goto(data.url);data.url='';await p.locator('#account').waitFor({state:'visible',timeout:30000});record(await p.evaluate(()=>!location.hash),'Email callback clears token URL');}
const local=async p=>p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('cleantime-he-v1'));return {date:s.date,from:s.from,gratitude:s.gratitude.map(g=>g.text)};});
(async()=>{browser=await chromium.launch({headless:!process.env.QA_MANUAL_EMAIL});try{
 const c1=await context(),p=await c1.newPage();p.on('response',async r=>{const u=new URL(r.url());if(u.origin===STAGE&&u.pathname.startsWith('/auth/v1/')&&r.status()>=400){try{const v=await r.json(),code=v.code||v.error_code||'';authErrors.push({path:u.pathname,status:r.status(),code:/^[a-z0-9_]+$/.test(code)?code:'unknown'});}catch{}}});p.on('dialog',d=>d.accept());
 phase='verify_preview';await p.goto(origin);const cfg=await p.evaluate(()=>({environment:window.CleanTimeBackend?.environment,url:window.CleanTimeBackend?.url,keyPublic:window.CleanTimeBackend?.key?.startsWith('sb_publishable_')}));record(cfg.environment==='preview'&&cfg.url===STAGE&&cfg.keyPublic,'Deployed Preview identifies isolated staging before any account/data writes');
 // This real request establishes the observed Auth destination without creating an account.
 let authTarget=false; p.on('request',r=>{const u=new URL(r.url());if(u.origin===STAGE&&u.pathname==='/auth/v1/otp')authTarget=true;});
 await p.locator('#onboardingLogin').click();await p.locator('#lEmail').fill('ct-unused-pr33@example.invalid');await p.locator('#lSend').click();await p.waitForFunction(()=>document.getElementById('syncMsg').textContent.includes('לא מצאנו חשבון'),{timeout:20000});record(authTarget&&productionAttempts===0,'Unused-email rejection reaches staging Auth with no production requests');
 await p.locator('#authBack').click();await p.locator('#welcomeStart').click();await p.locator('#oDate').fill('2026-10-01');await p.locator('#oFrom').selectOption('אחר');await p.locator('#guestForm button').click();await p.locator('#counter [data-go=gratitude]').click();await p.locator('#gInput').fill('CT staging synthetic gratitude');await p.locator('#gAdd').click();await p.reload();record(await p.locator('#counter').isVisible()&&(await local(p)).gratitude.includes('CT staging synthetic gratitude'),'Fresh guest useful action/reload preserves local content');
 const before=await local(p);await p.locator('#openSettings').click();await p.locator('#myAccount').click();await p.locator('#createAccount').click();await p.locator('#lEmail').fill(email);phase='send_signup';if(!process.env.QA_REUSE_SIGNUP_EMAIL){await p.locator('#lSend').click();await p.waitForFunction(()=>document.getElementById('syncMsg').textContent.includes('שלחנו קישור'),{timeout:20000});}record(JSON.stringify(await local(p))===JSON.stringify(before),process.env.QA_REUSE_SIGNUP_EMAIL?'Guest data retained before pending registration callback':'Guest data retained through real registration request');
 await receiveLink(p,'signup_email');record(await p.locator('#encryptionSetup').isVisible()&&!(await p.locator('#encryptionStatus').textContent()).includes('גיבוי מוצפן פעיל'),'Real verification continues to key setup without false active status');
 await p.locator('#finishBackupLater').click();await p.reload();await p.locator('#backupReminder').waitFor();record(await p.locator('#counter').isVisible()&&JSON.stringify(await local(p))===JSON.stringify(before),'Finish later/reload preserves guest history and reminder');await p.locator('#resumeBackup').click();
 await p.locator('#makeRecoveryKey').click();await p.locator('#recoveryGenerated').waitFor();let recovery=await p.locator('#recoveryOutput').inputValue();await p.locator('#recoverySaved').check();failWrite=true;await p.locator('#activateEncryption').click();await p.waitForFunction(()=>document.getElementById('encryptionMsg').textContent.includes('לא הושלם'));
 record(!(await p.locator('#encryptionStatus').textContent()).includes('גיבוי מוצפן פעיל')&&JSON.stringify(await local(p))===JSON.stringify(before),'Injected initial write failure retains content and truthful inactive status');
 failWrite=false;await p.locator('#retryEncryption').click();await p.waitForFunction(()=>document.getElementById('encryptionStatus').textContent.includes('גיבוי מוצפן פעיל')&&!JSON.parse(localStorage.getItem('cleantime-he-sync')).dirty);record(JSON.stringify(await local(p))===JSON.stringify(before),'Live encrypted write/readback retry verifies backup without content loss');
 await p.reload();await p.waitForFunction(()=>document.getElementById('encryptionStatus').textContent.includes('גיבוי מוצפן פעיל'));record(await p.locator('#counter').isVisible(),'Active trusted account reopens Today without key setup');
 // Real PostgREST/RLS/guard checks, returning only status/boolean results.
 await command('seed_peer_fixture');
 const api=await p.evaluate(async stage=>{
  const cfg=window.CleanTimeBackend,session=JSON.parse(localStorage.getItem('cleantime-he-auth')),headers={apikey:cfg.key,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'};
  const uid=session.user.id,base=stage+'/rest/v1/user_data',get=await fetch(base+'?user_id=eq.'+uid,{headers}),rows=await get.json(),row=rows[0];
  const peer=await fetch(base+'?user_id=eq.00000000-0000-4000-8000-000000000042',{headers}),peerRows=await peer.json();
  const anon=await fetch(base,{headers:{apikey:cfg.key}});
  const patch=async body=>{const r=await fetch(base+'?user_id=eq.'+uid,{method:'PATCH',headers,body:JSON.stringify(body)});const v=await r.json();return {status:r.status,code:v.code};};
  const plain=await patch({data:{synthetic:'rejected downgrade'}}),wrapper=await patch({data:{...row.data,wrapIv:row.data.wrapIv==='AAAAAAAAAAAAAAAA'?'AQAAAAAAAAAAAAAA':'AAAAAAAAAAAAAAAA'}}),move=await patch({user_id:'00000000-0000-4000-8000-000000000042'});
  const again=await fetch(base+'?user_id=eq.'+uid,{headers}),after=(await again.json())[0];
  return {encrypted:!!row.data.ciphertext&&row.data.v===1,peerInvisible:Array.isArray(peerRows)&&peerRows.length===0,anonDenied:!anon.ok,plainDenied:plain.code==='23514',wrapperDenied:wrapper.code==='23514',ownershipDenied:move.code==='42501',unchanged:JSON.stringify(after)===JSON.stringify(row)};
 },STAGE);
 for(const [label,ok] of Object.entries(api))record(ok,'Live database boundary: '+label);
 await p.locator('#openSettings').click();await p.locator('#myAccount').click();await p.locator('#signOut').click();await p.locator('#welcome').waitFor();record(await p.evaluate(()=>!localStorage.getItem('cleantime-he-v1')&&!localStorage.getItem('cleantime-he-crypto')),'Sign-out clears only the synthetic trusted-device state');
 const c2=await context(),p2=await c2.newPage();await p2.goto(origin);await p2.locator('#onboardingLogin').click();await p2.locator('#lEmail').fill(email);phase='send_existing';await p2.locator('#lSend').click();await p2.waitForFunction(()=>document.getElementById('syncMsg').textContent.includes('שלחנו קישור'),{timeout:20000});await receiveLink(p2,'existing_account_email');
 await p2.locator('#recoveryForm').waitFor();record(!await p2.locator('#encryptionSetup').isVisible(),'Second browser uses locked-backup restore rather than generating a replacement key');await p2.locator('#recoveryInput').fill(recovery);recovery='';await p2.locator('#unlockRecovery').click();await p2.waitForFunction(()=>document.getElementById('encryptionStatus').textContent.includes('גיבוי מוצפן פעיל'));record(JSON.stringify(await local(p2))===JSON.stringify(before),'Second-browser recovery key restores the live encrypted guest history');await p2.reload();await p2.waitForFunction(()=>document.getElementById('encryptionStatus').textContent.includes('גיבוי מוצפן פעיל'));record(await p2.locator('#counter').isVisible(),'Restored existing account reloads directly on Today');
 record(productionAttempts===0,'No production backend request attempted throughout live QA');
 fs.mkdirSync('.playwright-mcp/staging-qa',{recursive:true});await p2.screenshot({path:'.playwright-mcp/staging-qa/verified-restore.png',fullPage:true,mask:[p2.locator('#recoveryOutput'),p2.locator('#recoveryInput')]});process.stdout.write(JSON.stringify({complete:true,passed,productionRequests:productionAttempts})+'\n');
} catch(e){process.stdout.write(JSON.stringify({failed:true,phase,passed,errorName:e.name,authErrors})+'\n');process.exitCode=1;} finally{lines.close();await browser.close();}})();
